title: jl's first Github Pages
author: jl
email: gohxjl@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hello world

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
